---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        count_threshold: 3
        ruby:
          mass_threshold: 36
        javascript:
          mass_threshold: 80
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
      - 74f18007b920e8d81148d2f6a2756534
ratings:
  paths:
  - 'Gemfile.lock'
  - '**.erb'
  - '**.rb'
  - '**.js'
  - '**.jsx'
exclude_paths:
- app/assets/images/
- app/assets/javascripts/lib/
- frontend/src/patched/
- db/
- script/
- spec/
