---
engines:
  duplication:
    enabled: true
    config:
      languages:
        count_threshold: 3 # rule of three
        javascript:
          mass_threshold: 80 # default: 40
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - '**.js'
  - '**.jsx'
exclude_paths:
- public/images
- public/lib
- src/patched/
