sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - app/assets/javascripts/node_modules
rvm:
  - 2.3.0
before_script:
  - echo "Rspec setup"
  - export RAILS_ENV=test
  - cp .example-env .env
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - echo "node setup"
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - bundle exec rspec && npm test && bundle exec brakeman -q -z
