#%RAML 1.0
---
title: Metamaps
version: v2
baseUri: http://metamaps.cc/api/v2
mediaType: application/json

traits:
  - pageable: !include traits/pageable.raml
  - orderable: !include traits/orderable.raml
  - searchable: !include traits/searchable.raml

schemas:
  - topic: !include schemas/topic.json

resourceTypes:
  - base: !include resourceTypes/base.raml
  - item: !include resourceTypes/item.raml
  - collection: !include resourceTypes/collection.raml

/topics: !include apis/topics.raml
